window:
  width: 1000
  height: 1000
  subtitle: "Base"
drawing:
  scale: 0.25
  size: 256
  draw_trajectory: false
  draw_sensors: false
  draw_comms: false
camera:
  viewport_margin: 400
  speed: 0.2
  focus_timer: 100
simulation:
  bot_count: 1
  sim_steps: 200
  map_generator:
    grid_width: 30
    grid_height: 30
    grid_seed: 12345
    cellular:
      start_alive_chance: 0.5
      death_limit: 5
      birth_limit: 5
      steps: 5
  robot:
    map_resolution: high
    sensor:
      count: 4
      beam_grid_scale: 2
      range_grid_scale: 10
    comms:
      wireless_range_grid_scale: 10
      update_period: 1
    name_generator:
      - - Red
        - Green
        - Blue
      - - Wolf
        - Dragon
      - - Fang
        - Claw